/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#006eca",
        "inverse-surface": "#2d3133",
        "outline": "#707a6c",
        "on-surface-variant": "#40493d",
        "surface-tint": "#1b6d24",
        "secondary-fixed": "#98f994",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "on-primary-container": "#cbffc2",
        "on-secondary-fixed": "#002204",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#f7f9fc",
        "surface-bright": "#f7f9fc",
        "surface-container-high": "#e6e8eb",
        "inverse-primary": "#88d982",
        "on-primary-fixed-variant": "#005312",
        "on-primary-fixed": "#002204",
        "error-container": "#ffdad6",
        "primary": "#0d631b",
        "on-tertiary-fixed": "#001c3a",
        "surface-variant": "#e0e3e6",
        "tertiary-fixed-dim": "#a5c8ff",
        "primary-fixed-dim": "#88d982",
        "on-secondary-fixed-variant": "#005313",
        "on-tertiary-fixed-variant": "#004786",
        "on-surface": "#191c1e",
        "tertiary": "#00569f",
        "secondary-container": "#98f994",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d4e3ff",
        "primary-fixed": "#a3f69c",
        "on-background": "#191c1e",
        "surface-container": "#eceef1",
        "surface-container-highest": "#e0e3e6",
        "background": "#f7f9fc",
        "surface-dim": "#d8dadd",
        "primary-container": "#2e7d32",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#7ddc7a",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#bfcaba",
        "on-secondary-container": "#0c7521",
        "inverse-on-surface": "#eff1f4",
        "secondary": "#006e1c",
        "on-tertiary-container": "#ebf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        "gutter": "16px",
        "base": "8px",
        "container-padding": "24px",
        "section-gap": "32px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
