import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { farmService, predictionService } from '../services/api';

export const AIRecommendationsPage: React.FC = () => {
  const { data: farmsData } = useQuery({
    queryKey: ['farms'],
    queryFn: () => farmService.getFarms(1, 50),
  });

  const firstFarm = farmsData?.items[0];

  const { data: recommendation, isLoading } = useQuery({
    queryKey: ['recommendations', firstFarm?.id],
    queryFn: () => predictionService.getRecommendations(firstFarm!.id),
    enabled: !!firstFarm,
  });

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-headline-lg font-headline-lg text-on-surface">AI Irrigation & Crop Recommendations</h2>
        <p className="text-body-md text-on-surface-variant">
          Autonomous recommendations generated by AgriNova Scikit-Learn ML Engine
        </p>
      </div>

      {isLoading ? (
        <div className="flex justify-center p-12">
          <span className="material-symbols-outlined text-3xl text-primary animate-spin">sync</span>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Primary Recommendation Main Card */}
          <div className="lg:col-span-8 bg-surface-container-lowest rounded-xl border border-outline-variant/20 p-8 shadow-sm space-y-6">
            <div className="flex justify-between items-start flex-wrap gap-2">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-primary-container text-on-primary-container flex items-center justify-center shadow-sm">
                  <span className="material-symbols-outlined">psychology</span>
                </div>
                <div>
                  <h3 className="text-headline-md font-headline-md text-on-surface">
                    {recommendation?.farm_name || 'North Field Beta'}
                  </h3>
                  <span className="text-xs text-on-surface-variant">
                    Generated: {recommendation?.predicted_at ? new Date(recommendation.predicted_at).toLocaleDateString() : 'Today'}
                  </span>
                </div>
              </div>

              <span
                className={`px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider ${
                  recommendation?.urgency === 'immediate'
                    ? 'bg-error-container text-on-error-container'
                    : recommendation?.urgency === 'within_48h'
                    ? 'bg-[#F59E0B]/20 text-[#B45309]'
                    : 'bg-primary-container/20 text-primary'
                }`}
              >
                Urgency: {recommendation?.urgency?.replace('_', ' ') || 'Within 48h'}
              </span>
            </div>

            {/* Main Action Banner */}
            <div className="p-6 rounded-xl bg-gradient-to-r from-primary-container/10 via-surface-container to-transparent border border-primary/20 space-y-3">
              <span className="text-xs font-bold uppercase text-primary tracking-wider">Primary Action Required</span>
              <p className="text-body-lg text-on-surface leading-relaxed font-medium">
                {recommendation?.primary_recommendation ||
                  'AI predicts moderate moisture stress in the western section of your farm within 48 hours. Apply 30mm irrigation.'}
              </p>
            </div>

            {/* Action Checklist */}
            <div>
              <h4 className="text-label-md font-label-md font-semibold text-on-surface mb-3">
                Secondary Recommendations & Best Practices
              </h4>
              <ul className="space-y-3">
                {(recommendation?.secondary_recommendations || [
                  'Inspect the north-east sector first — highest stress concentration likely.',
                  'Check irrigation system for blockages or pressure drops.',
                  'Consider splitting irrigation into 2 sessions to maximize absorption.',
                  'Monitor NDVI daily until stress returns to healthy range.',
                ]).map((rec, i) => (
                  <li key={i} className="flex items-start gap-3 p-3 rounded-lg bg-surface-container/50 border border-outline-variant/10 text-sm text-on-surface">
                    <span className="material-symbols-outlined text-primary text-[20px] mt-0.5">check_circle</span>
                    <span>{rec}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Side Metrics Card */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bg-surface-container-lowest rounded-xl border border-outline-variant/20 p-6 shadow-sm space-y-4">
              <h4 className="text-headline-md font-headline-md text-on-surface">Prediction Metrics</h4>

              <div className="space-y-3">
                <div className="flex justify-between items-center text-sm border-b border-outline-variant/20 pb-2">
                  <span className="text-on-surface-variant">Stress Score</span>
                  <span className="font-bold text-on-surface text-lg">
                    {recommendation?.stress_score ?? 35} / 100
                  </span>
                </div>

                <div className="flex justify-between items-center text-sm border-b border-outline-variant/20 pb-2">
                  <span className="text-on-surface-variant">AI Confidence</span>
                  <span className="font-bold text-primary text-lg">
                    {recommendation?.confidence ?? 92}%
                  </span>
                </div>

                <div className="flex justify-between items-center text-sm border-b border-outline-variant/20 pb-2">
                  <span className="text-on-surface-variant">Est. Water Need</span>
                  <span className="font-bold text-tertiary text-lg">
                    {recommendation?.estimated_water_need ?? 450} L/ha
                  </span>
                </div>

                <div className="flex justify-between items-center text-sm">
                  <span className="text-on-surface-variant">Next Analysis Due</span>
                  <span className="font-semibold text-on-surface">
                    {recommendation?.next_prediction_due || 'In 3 days'}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
